# 
# Overwrite environment variables and use absolute paths instead of %S and %E
# since the unit is started by the system manager (as root)
#
[Service]
# reset complete environment to avoid conflicts
Environment=
EnvironmentFile=/etc/openshell/config/gateway-qm.env

ProtectSystem=true
