# 
# Overwrite environment variables and use absolute paths instead of %S and %E
# since the unit is started by the system manager (as root)
#
[Service]
# reset complete environment to avoid conflicts
Environment=

# Set environment variables used by OpenShell internally for locating files
Environment=HOME=/etc/openshell
Environment=XDG_CONFIG_HOME=/etc/openshell/config
Environment=XDG_STATE_HOME=/etc/openshell/state
Environment=XDG_RUNTIME_DIR=/run

EnvironmentFile=/etc/openshell/config/gateway-tls.env

# Use empty ExecStartPre= and StateDirectory= to reset previous entries and do not run
# init-pki and init-gateway as static files are used
ExecStartPre=
